CREATE TABLE Authors (
    id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY
        (START WITH 1, INCREMENT  BY 1),
    name VARCHAR(50) NOT NULL,
    lastname VARCHAR (60) NOT NULL,
    BirthDay VARCHAR (30) NOT NULL,
    DeathDay VARCHAR (30),
    PRIMARY KEY (id)
)