CREATE TABLE Clients (
    id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY
        (START WITH 1, INCREMENT  BY 1),
    name VARCHAR(50) NOT NULL,
    lastname VARCHAR(50) NOT NULL,
    phoneNumber VARCHAR(20) NOT NULL,
    emailAddress VARCHAR (40) NOT NULL,
    Address VARCHAR (40) NOT NULL,
    PRIMARY KEY (id)
)